Repository Nexters/momo-server, pull requests merged in 2023-02, with the labels that each got.

#23 [Feat/#19] 인증 및 인가 예외 처리, 로그아웃 구현
  build.gradle
  src/main/java/com/nexters/momo/common/response/ResponseCodeAndMessages.java
  src/main/java/com/nexters/momo/config/RedisConfig.java
  src/main/java/com/nexters/momo/config/SecurityConfig.java
  src/main/java/com/nexters/momo/member/auth/application/MemberContext.java
  src/main/java/com/nexters/momo/member/auth/application/MemberDetailsService.java
  src/main/java/com/nexters/momo/member/auth/application/MemberService.java
  src/main/java/com/nexters/momo/member/auth/application/RedisCachingService.java
  src/main/java/com/nexters/momo/member/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/nexters/momo/member/auth/filter/LoginAuthenticationFilter.java
  src/main/java/com/nexters/momo/member/auth/handler/JwtLogoutHandler.java
  src/main/java/com/nexters/momo/member/auth/handler/JwtLogoutSuccessHandler.java
  src/main/java/com/nexters/momo/member/auth/handler/LoginAuthenticationEntryPoint.java
  src/main/java/com/nexters/momo/member/auth/handler/LoginAuthenticationSuccessHandler.java
  src/main/java/com/nexters/momo/member/auth/handler/LoginDeniedHandler.java
  src/main/java/com/nexters/momo/member/auth/jwt/JwtTokenFactory.java
  src/main/java/com/nexters/momo/member/auth/presentation/AuthController.java
  src/main/java/com/nexters/momo/member/auth/provider/LoginAuthenticationProvider.java
  src/main/java/com/nexters/momo/member/auth/utils/AuthorizationExtractor.java
  src/main/java/com/nexters/momo/member/auth/utils/AuthorizationType.java
  src/test/java/com/nexters/momo/acceptance/AuthAcceptanceTest.java
  src/test/java/com/nexters/momo/acceptance/AuthStep.java
  src/test/java/com/nexters/momo/acceptance/RandomPortConfigure.java
  src/test/java/com/nexters/momo/common/TestRedisContainer.java
  src/test/resources/application.yml
Labels: feat

#30 [Feat/#27] GitHub Action 적용
  .github/workflows/deploy.yml
Labels: setting

#28 [Feat/#26] 회원 정보 조회와 Role hierarchy 구현
  src/main/java/com/nexters/momo/config/SecurityConfig.java
  src/main/java/com/nexters/momo/member/auth/application/MemberService.java
  src/main/java/com/nexters/momo/member/auth/application/RoleHierarchyService.java
  src/main/java/com/nexters/momo/member/auth/domain/Member.java
  src/main/java/com/nexters/momo/member/auth/domain/MemberQueryRepository.java
  src/main/java/com/nexters/momo/member/auth/domain/MemberQueryRepositoryImpl.java
  src/main/java/com/nexters/momo/member/auth/domain/MemberRepository.java
  src/main/java/com/nexters/momo/member/auth/domain/Name.java
  src/main/java/com/nexters/momo/member/auth/domain/RoleHierarchy.java
  src/main/java/com/nexters/momo/member/auth/domain/RoleHierarchyRepository.java
  src/main/java/com/nexters/momo/member/auth/handler/JwtLogoutSuccessHandler.java
  src/main/java/com/nexters/momo/member/auth/listener/SetupDataLoader.java
  src/main/java/com/nexters/momo/member/auth/utils/SecurityInitializer.java
  src/main/java/com/nexters/momo/member/mypage/common/dto/response/AttendanceDto.java
  src/main/java/com/nexters/momo/member/mypage/common/dto/response/MemberInfoDto.java
  src/main/java/com/nexters/momo/member/mypage/common/dto/response/MemberLookUpResponse.java
  src/main/java/com/nexters/momo/member/mypage/presentation/MyPageController.java
  src/test/java/com/nexters/momo/acceptance/AuthAcceptanceTest.java
  src/test/java/com/nexters/momo/acceptance/AuthStep.java
  src/test/java/com/nexters/momo/acceptance/MyPageAcceptanceTest.java
  src/test/java/com/nexters/momo/acceptance/MyPageStep.java
  src/test/java/com/nexters/momo/session/service/SessionServiceTest.java
Labels: feat

#37 [Feat/#21] Session 이미지 관련 기능 추가
  build.gradle
  src/main/java/com/nexters/momo/file/util/FileUtil.java
  src/main/java/com/nexters/momo/session/application/SessionImageService.java
  src/main/java/com/nexters/momo/session/application/dto/SessionDto.java
  src/main/java/com/nexters/momo/session/domain/SessionImage.java
  src/main/java/com/nexters/momo/session/domain/SessionImageRepository.java
  src/main/java/com/nexters/momo/session/presentation/SessionApiSpec.java
  src/main/java/com/nexters/momo/session/presentation/SessionController.java
  src/main/java/com/nexters/momo/session/presentation/dto/SessionResponse.java
  src/main/resources/application-dev.yml
  src/test/java/com/nexters/momo/session/application/SessionImageServiceTest.java
  src/test/java/com/nexters/momo/session/application/SessionServiceTest.java
  src/test/java/com/nexters/momo/session/domain/SessionImageTest.java
  src/test/resources/application.yml
Labels: feat

#40 [Feat/#39] AWS 엘라스틱 빈스톡 및 GitHub Action 도입
  .ebextensions/00-makeFiles.config
  .github/workflows/deploy.yml
  Procfile
Labels: setting

#44 [Feat/#38] 세션 참여 API 구현
  src/main/java/com/nexters/momo/attendance/application/AttendanceService.java
  src/main/java/com/nexters/momo/attendance/application/dto/AttendanceDto.java
  src/main/java/com/nexters/momo/attendance/domain/AttendanceRepository.java
  src/main/java/com/nexters/momo/attendance/presentation/AttendanceController.java
  src/main/java/com/nexters/momo/attendance/presentation/dto/MemberAttendanceRequest.java
Labels: feat

#48 [Refactor/#47] Attendacne Service Refactoring
  src/main/java/com/nexters/momo/attendance/application/AttendanceService.java
  src/main/java/com/nexters/momo/attendance/domain/Attendance.java
  src/main/java/com/nexters/momo/attendance/presentation/AttendanceApiSpec.java
  src/main/java/com/nexters/momo/attendance/presentation/AttendanceController.java
  src/main/java/com/nexters/momo/session/domain/Session.java
  src/test/java/com/nexters/momo/acceptance/MyPageStep.java
Labels: refactor
